bounds   = [
    [-32, 32], 
    [-32, 32], 
    [-32, 32], 
    [-32, 32], 
    [-32, 32], 
    [-32, 32], 
    [-32, 32], 
    [-32, 32], 
    [-32, 32], 
    [-32, 32]
]
var_name   = ["x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10"]
num_init   = 4
batch_size = 4
max_iter   = 1
use_sobol  = 1
warp       = 0
mo_eval    = 300
